API_KEY = "93869da722c946a5874132428250105"

OPENAI_API_KEY = "8Ajv1KW1w2k1YtNOiOib7wR2GpPJfV9rUsyjStqAsiqIHyEDp64GJQQJ99BCACYeBjFXJ3w3AAABACOGO4T1"
OPENAI_API_ENDPOINT = "https://streamlit-oai.openai.azure.com/"